services:
  - type: web
    name: dynastorev2-frontend
    env: static
    buildCommand: npm install && npm run build
    staticPublishPath: ./dist
    routes:
      - type: rewrite
        source: /*
        destination: /index.html
    envVars:
      - key: VITE_API_URL
        value: https://dynastorev2-backend-1.onrender.com/api
      - key: VITE_SUPABASE_URL
        value: https://itvnbmgjrqawgqqrwwds.supabase.co
      - key: VITE_SUPABASE_ANON_KEY
        value: sb_publishable_EFykqWB-Tvd4W3vdvZCk1g_ycajcyVt
      - key: VITE_GOOGLE_CLIENT_ID
        value: 757134176189-d2pm2559geqom3372so6p0t6d56il34m.apps.googleusercontent.com
